-- MySQL Script generated by MySQL Workbench
-- 03/01/17 17:02:11
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`studie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`studie` (
  `idstudie` INT NOT NULL AUTO_INCREMENT,
  `studie_navn` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idstudie`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`medlemmer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`medlemmer` (
  `id_medlem` INT NOT NULL AUTO_INCREMENT,
  `form_fornavn` VARCHAR(45) NOT NULL,
  `form_etternavn` VARCHAR(45) NOT NULL,
  `form_epost` VARCHAR(45) NOT NULL,
  `form_tlf` INT NULL,
  `studie_idstudie` INT NOT NULL,
  PRIMARY KEY (`id_medlem`),
  INDEX `fk_medlemmer_studie_idx` (`studie_idstudie` ASC),
  CONSTRAINT `fk_medlemmer_studie`
    FOREIGN KEY (`studie_idstudie`)
    REFERENCES `mydb`.`studie` (`idstudie`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
